# Generated by Django 5.2.6 on 2025-10-01 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('R', models.FloatField(help_text='Resistencia en Ohmios')),
                ('C', models.FloatField(help_text='Capacitancia en Faradios')),
                ('V0', models.FloatField(help_text='Voltaje inicial')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('voltage', models.FloatField(help_text='Voltaje medido en V')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='monitoreo.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField(help_text='Tiempo de simulación en segundos')),
                ('voltage', models.FloatField(help_text='Voltaje calculado con Euler')),
                ('h', models.FloatField(help_text='Paso usado en Euler (s)')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='monitoreo.experiment')),
            ],
        ),
    ]
