# Generated by Django 5.2.6 on 2025-10-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0002_remove_experimentdata_experiment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulationdata',
            old_name='timestamp',
            new_name='timems',
        ),
        migrations.RemoveField(
            model_name='experimentdata',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='experimentdata',
            name='timems',
            field=models.FloatField(default=0.0, help_text='Tiempo de medición en ms'),
        ),
    ]
